#!/bin/bash

BASE_REPO=ruby
VARIANTS=(browsers node node-browsers)


function generate_node_variant() {
  DESIRED_NODE_TAG=$1

  cat <<'EOF'
FROM {{BASE_IMAGE}}

# node installations command expect to run as root
USER root
EOF

  NODE_MANIFEST_INFO=$(curl https://raw.githubusercontent.com/docker-library/official-images/master/library/node |grep -A2 $DESIRED_NODE_TAG)
  NODE_GIT_COMMIT=$(printf "%s\n" "${NODE_MANIFEST_INFO}" | grep GitCommit | awk '{print $2;}')
  NODE_DIRECTORY=$(printf "%s\n" "${NODE_MANIFEST_INFO}" | grep Directory | awk '{print $2;}')
  
  NODE_DOCKERFILE_URL="https://raw.githubusercontent.com/nodejs/docker-node/${NODE_GIT_COMMIT}/${NODE_DIRECTORY}/Dockerfile"
  echo "## Using node installation from $NODE_DOCKERFILE_URL"
  curl -sSL $NODE_DOCKERFILE_URL | grep -v -e '^FROM buildpack-deps:jessie' -e '^CMD'

  echo ''
  echo 'USER circleci'
}

function generate_node_browser_variant() {
  echo 'FROM {{BASE_IMAGE}}-node'
  cat ../shared/images/Dockerfile-browsers.template | grep -v '^FROM'
}

mkdir -p resources
generate_node_variant "latest" > resources/Dockerfile-node.template
generate_node_browser_variant > resources/Dockerfile-node-browsers.template

source ../shared/images/generate.sh
