#!/bin/bash

NAME=Ruby
BASE_REPO=ruby
VARIANTS=(browsers node node-browsers)
IMAGE_CUSTOMIZATIONS='
RUN if [[ ${BUNDLER_VERSION} == "1.16.0" ]]; then gem uninstall -a -x --force bundler && \
  gem install bundler -v "1.15.4"; fi
'

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
