#!/bin/bash

NAME="Go (golang)"
BASE_REPO=golang
VARIANTS=(browsers)

IMAGE_CUSTOMIZATIONS='
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | INSTALL_DIRECTORY=/usr/local/bin sh
'

source ../shared/images/generate.sh
