#!/bin/bash

NAME="Go (Golang)"
BASE_REPO=golang
VARIANTS=(browsers node node-browsers)

IMAGE_CUSTOMIZATIONS='
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | INSTALL_DIRECTORY=/usr/local/bin sh
'

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
