#!/bin/bash

set -eu

TEMPLATE=$1
BASE_IMAGE=$2
NEW_IMAGE=$3

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function build() {
	echo "==> Building $NEW_IMAGE"
	rm -rf workdir; mkdir -p workdir
	cat ${DIR}/Dockerfile-${TEMPLATE}.template | sed "s|{{BASE_IMAGE}}|$BASE_IMAGE|g" > workdir/Dockerfile

	pushd workdir
	pwd
	ls *
        docker build -t ${NEW_IMAGE} .
	popd
}

build
