#!/bin/bash

set -eu

TEMPLATE=$1
BASE_REPO=$2
NEW_IMAGE_REPO=$3
BASE_MANIFEST=$4

VARIANT_TAG=$5

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BASE_TAGS=$(
  curl -sSL "$BASE_MANIFEST" \
    | grep Tags \
    | sed  's/Tags: //g' \
    | sed 's|, | |g' \
    |grep -v -e '-'
)

for tag in $BASE_TAGS
do
  ${DIR}/build $TEMPLATE "${BASE_REPO}:${tag}" "${NEW_IMAGE_REPO}:${tag}${VARIANT_TAG}"
done

