#!/usr/bin/env bash
#
# Copy the latest Dockerfile and README for each image, to use as an example on Docker Hub
#
set -eu -o pipefail

target="${EXAMPLE_TARGET-/tmp/example-images}"
image="$1"

mkdir -p "/tmp/example-images/$image"
cd "${image}"


dockerfile=""
if [ -f images/latest/Dockerfile ]; then
    dockerfile=images/latest/Dockerfile
elif grep -qs -l latest images/*/ALIASES; then
    dockerfile="$(grep -l latest images/*/ALIASES | head -1 | xargs -r dirname | xargs -I{} echo {}/Dockerfile)"
else
    # Fallback to any Dockerfile
    dockerfile="$(find . -name Dockerfile -type f | head -1)"
fi

cp -v "$dockerfile"  "/tmp/example-images/$image/"

find . -name README.md -type f | head -1 | xargs -I{} cp -v {} "/tmp/example-images/$image"

sed -i 's|DO NOT MODIFY THIS FILE.  THIS FILE HAS BEEN AUTOGENERATED|this Dockerfile is an example representing one variant of this image;\n### please see https://github.com/circleci-public/circleci-dockerfiles\n### for a complete list of Dockerfiles for each tag/variant of this image|g' "/tmp/example-images/$image/Dockerfile"

sed -i '1,5d' "/tmp/example-images/$image/README.md"
