#!/bin/bash

NAME=Java
BASE_REPO=openjdk
VARIANTS=(browsers node node-browsers)

TAG_FILTER="grep -v -e ^7 -e ^6 -e jre"

function generate_customizations() {

  MAVEN_VERSION=$(./java_helper maven)
  ANT_VERSION=$(./java_helper ant)
  GRADLE_VERSION=$(./java_helper gradle)
  SBT_URL=$(./java_helper sbt)

  cat <<EOF

# Install Maven Version: $MAVEN_VERSION
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/apache-maven.tar.gz \
    https://www.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && tar xf /tmp/apache-maven.tar.gz -C /opt/ \
  && rm /tmp/apache-maven.tar.gz \
  && ln -s /opt/apache-maven-* /opt/apache-maven \
  && /opt/apache-maven/bin/mvn -version

# Install Ant Version: $ANT_VERSION
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/apache-ant.tar.gz \
    https://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz \
  && tar xf /tmp/apache-ant.tar.gz -C /opt/ \
  && ln -s /opt/apache-ant-* /opt/apache-ant \
  && rm -rf /tmp/apache-ant.tar.gz \
  && /opt/apache-ant/bin/ant -version

ENV ANT_HOME=/opt/apache-ant

# Install Gradle Version: $GRADLE_VERSION
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/gradle.zip \
    https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip \
  && unzip -d /opt /tmp/gradle.zip \
  && rm /tmp/gradle.zip \
  && ln -s /opt/gradle-* /opt/gradle \
  && /opt/gradle/bin/gradle -version

# Install sbt from $SBT_URL
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/sbt.tgz ${SBT_URL} \
  && tar -xzf /tmp/sbt.tgz -C /opt/ \
  && rm /tmp/sbt.tgz \
  && /opt/sbt/bin/sbt sbtVersion

EOF

  # Modify path but don't inject builder path in there!
  cat <<'EOF'
# Update PATH for Java tools
ENV PATH="/opt/sbt/bin:/opt/apache-maven/bin:/opt/apache-ant/bin:/opt/gradle/bin:$PATH"

# smoke test with path
RUN mvn -version
RUN ant -version
RUN gradle -version
RUN sbt sbtVersion

EOF
}

IMAGE_CUSTOMIZATIONS=$(generate_customizations)

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
