#!/bin/bash

set -eu


../../shared/images/build-all \
	basic \
	python \
	circleci-library/python \
	https://raw.githubusercontent.com/docker-library/official-images/master/library/python

../../shared/images/build-all \
	browsers \
	circleci-library/python \
	circleci-library/python \
	https://raw.githubusercontent.com/docker-library/official-images/master/library/python \
	-browsers
