FROM {{BASE_IMAGE}}

ENV POSTGRES_USER=root \
    POSTGRES_DB=circle_test

# This is performance optimization tweak to make DB faster
RUN if [ -e /usr/local/share/postgresql/postgresql.conf.sample ]; then \
        postgresfile=/usr/local/share/postgresql/postgresql.conf.sample; \
    else \
        postgresfile=/usr/share/postgresql/postgresql.conf.sample; \
    fi && \
    echo '\n\
fsync=off\n\
synchronous_commit=off\n\
full_page_writes=off\n\
bgwriter_lru_maxpages=0\n' >> $postgresfile
