#!/bin/bash

NAME=Python
BASE_REPO=python
VARIANTS=(browsers node node-browsers)

IMAGE_CUSTOMIZATIONS=$(cat <<'EOF'

# Install pipenv and poetry
RUN sudo pip install --no-cache pipenv poetry

EOF
)

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
