#!/bin/bash

set -eu


../../shared/images/build-all \
	basic \
	node \
	circleci-library/node \
	https://raw.githubusercontent.com/docker-library/official-images/master/library/node

../../shared/images/build-all \
	browsers \
	circleci-library/node \
	circleci-library/node \
	https://raw.githubusercontent.com/docker-library/official-images/master/library/node \
	-browsers
