#!/bin/bash

NAME=PHP
BASE_REPO=php
VARIANTS=(browsers node node-browsers)

TAG_FILTER="grep -v -e rc -e beta"

IMAGE_CUSTOMIZATIONS=$(cat <<'EOF'

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

RUN pecl install xdebug && docker-php-ext-enable xdebug

EOF
)

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
