#!/bin/bash

NAME=PHP
BASE_REPO=php
VARIANTS=(browsers node node-browsers)

TAG_FILTER="grep -v -e rc -e beta"

IMAGE_CUSTOMIZATIONS=$(cat <<'EOF'

# Install composer
RUN php -r "copy('https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

# xdebug is not compatible with 7.2 yet
RUN if [[ $(php-config --version) = 7.2* ]]; then echo "skipping xdebug, not supported"; else pecl install xdebug && docker-php-ext-enable xdebug; fi

EOF
)

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
